name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run java checkstyle
        run: ./gradlew autoLintGradle -x test -x jacocoTestReport

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run:  ./gradlew assemble -x autoLintGradle -x jacocoTestReport

      - name: Run tests
        run: ./gradlew test -x autoLintGradle -x jacocoTestReport

      - name: Run jacoco
        run: ./gradlew jacocoTestReport -x test -x autoLintGradle

      - name: Test coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html



